### ISSUE TITLE
License for your ARKit Template

### ISSUE THREAD

**Issue by campanileLabs** [hanleyweng/iOS-Stereoscopic-ARKit-Template#1]
Hi I would like to use your ARKit template for my app. the problem is it doesn't have a license can you please tell me the terms and conditions of your template. I am willing to compensate you for the setup.

Thanks,
Edsel

**Comment by hanleyweng** [comment]
Hi Edsel, Thanks for asking! It's just a few lines of experimental code. Go ahead and use it, experiment with it, however you like. No attributions or compensation needed. 

Not too familiar with licenses, did a quick search, and the MIT License looks the most open - so let's go with that. – https://choosealicense.com/licenses/mit/

Keep in mind that if you are planning to use this for a commercial app, iOS11 is still in beta. Also be sure to read the footnotes - you may need to alter the code depending on what you want to do.

**Comment by campanileLabs** [comment]
ty
